
version: 0.2

phases:
  build:
    commands:
      - |
        echo '{
          "family": "new-task",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "1024",
          "memory": "2048",
          "executionRoleArn": "'$ROLE'",
          "containerDefinitions": [
            {
              "name": "frontend_container",
              "image": "435495016122.dkr.ecr.ap-southeast-1.amazonaws.com/my_ecr_repo:green",
              "essential": true,
              "portMappings": [
                {
                  "containerPort": 3000,
                  "hostPort": 3000
                }
              ]
            },
            {
              "name": "backend_container",
              "image": "435495016122.dkr.ecr.ap-southeast-1.amazonaws.com/my_ecr_repo:backend",
              "portMappings": [{"containerPort": 5000, "hostPort": 5000}],
              "essential": true,
              "environment": [
                {
                  "name": "DB_HOST",
                  "value": "'$DB_HOST'"
                },
                {
                  "name": "DB_NAME",
                  "value": "'$DB_NAME'"
                },
                {
                  "name": "DB_USER",
                  "value": "'$DB_USER'"
                },
                {
                  "name": "DB_PASSWORD",
                  "value": "'$DB_PASSWORD'"
                }
              ]
            }
          ]
        }' > imagedefinitions.json

        export TaskArn=$(aws ecs register-task-definition --cli-input-json file://imagedefinitions.json --query "taskDefinition.taskDefinitionArn" --output text)
        echo "Task ARN:'$TaskArn'"

        echo "Creating appspec.yml..."
        cat <<EOF > appspec.yml
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: "$TaskArn"
                LoadBalancerInfo:
                  ContainerName: "frontend_container"
                  ContainerPort: 3000
        EOF

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
  name: MyGeneratedArtifacts
